[custom.all.array]
type   = "local"
path   = "."
ipkg   = "array.ipkg"
test   = "test/test.ipkg"

[custom.all.darray]
type   = "local"
path   = "darray"
ipkg   = "darray.ipkg"
test   = "test/test.ipkg"

[custom.all.array-docs]
type   = "local"
path   = "docs"
ipkg   = "docs.ipkg"

[custom.all.array-profile]
type   = "local"
path   = "profile"
ipkg   = "profile.ipkg"

[custom.all.enum]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-enum"
commit = "latest:main"
ipkg   = "enum.ipkg"

[custom.all]
ref1.commit       = "latest:main"
bytestring.commit = "latest:main"
algebra.commit    = "latest:main"
